### PR TITLE
Realized checklist based story point progression (Issue #24)

### PR DESCRIPTION
**Pull request by Electrenator**
Added enhancement from issue luckyshot/agilescrumfortrello#24.
This is implemented with the fractional story points in mind. It assigns equal weight to each checkbox item by calculating the story points left on a card.

Image of this working follows; 
Checklist based story point progression working as intended

Note: This does not update the fractional story points assigned in the title or the top right of a card, which is intended.

### CODE REVIEW

**Comment by Electrenator** [comment]
Nice, @luckyshot I see you added this to the new version of agilescrumfortrello. Any idea when this update will be available in the chrome store or in firefox addons?

**Comment by Electrenator** [comment]
Well, I guess I contributed to a dying project. Should have noticed that beforehand

**Comment by luckyshot** [comment]
> I guess I contributed to a dying project

It's not dying, I'm not retiring it any time soon. I'm just not actively developing it but I keep maintaining, updating and managing it. 

I myself consider it feature complete, something we aren't used to these days when everything needs tons of extra features added to it every day to keep it cool, introducing new bugs and making it slower and slower.

> Any idea when this update will be available in the chrome store or in firefox addons?

I submitted it to the Chrome Store a few minutes after approving your PR so it's just a matter of waiting for Google Review Team to publish it, usually a few minutes or hours. 

In the case of Firefox, it needs some tweaking to get it working and I don't have Firefox so I can't release it there at the moment.

**Comment by Electrenator** [comment]
> In the case of Firefox, it needs some tweaking to get it working and I don't have Firefox so I can't release it there at the moment.

I primarily use Firefox. Because of this it now makes sense why I haven't seen the extension update yet. As far as I know, it will work on Firefox. I have written my changes using that browser so I'm certain that it should work over there.

The thought of this project dying mostly came from the really inactive issue section with inactive issues. Probably should have expressed that differently to take into account that you did approve my pull-request and update the application on Chrome.

Lastly, I get that you see the program as feature-complete and that the development has been inactive because of that. I just think there can still be some speed improvements made. This especially in the realm of speed with making operations asynchronous. Get it if you don't want to address those things or if you lost interest in this. This project was started in 2015 after all.

**Pull request merged**
